### ISSUE TITLE
The Sound Info node has no outputs?

### ISSUE THREAD

**Issue by TK-1214** [negdo/Sound_Nodes#9]
I was trying the Lite Version to consider purchasing the full version, however it does not seem to work correctly or I'm missing something. It works correctly on Blender 3.6.9 but not 4.0.2 or 4.1, but since on Blender Market it says versions 4.0, 3.6, 3.5, 3.4, 3.3 I thought at least it should work on 4.0.2 as well? 

If it is supposed to work in 4.0.2 or 4.1, here is the error message I got for troubleshooting (in both versions the same):

`Error: Python: Traceback (most recent call last):
  File "C:\Users\gbrinkmann\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sound_Nodes-main\compute.py", line 104, in execute
    generate_chromagram()
  File "C:\Users\gbrinkmann\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Sound_Nodes-main\generate_nodes.py", line 75, in generate_chromagram
    chromagram.outputs.new('NodeSocketFloat',tone)
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'GeometryNodeTree' object has no attribute 'outputs'`
